<?php
acf_add_local_field_group(array(
    'key'                           => 'group_page_5G9hFG9cgxnmHEHT',
    'title'                         => esc_attr__('Blog Post Options','keymoto'),
    'fields' => array(
        /*-------------------------------------------------------------------
        ==  Blog Setting
        -------------------------------------------------------------------*/
        array(
            'key'                   => 'field_XS5vnP8HHQGBF',
            'label'                 => '<span class="dashicons dashicons-grid-view"></span>'.esc_attr__('Blog Setting','keymoto'),
            'name'                  => '',
            'type'                  => 'tab',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'placement'             => 'left',
            'endpoint'              => 0,
        ),
        array(
            'key'                   => 'field_RSzSD1O0niiyA',
            'label'                 => esc_attr__('Post Style','keymoto'),
            'name'                  => 'blog_archive_style',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'default'                       => esc_attr__('Default','keymoto'),
                'default-two'                   => esc_attr__('Default Two','keymoto'),
                'grid'                          => esc_attr__('Grid','keymoto'),
            ),
            'default_value' => array(
                0                                   => 'default',
            ),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),

        array(
            'key'                   => 'field_fUdpQeSH3x3WCym5',
            'label'                 => esc_attr__('Post per page','keymoto'),
            'name'                  => 'post_per_page',
            'type'                  => 'text',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                                 => '',
                'class'                                 => '',
                'id'                                    => '',
            ),
            'choices'               => array(),
            'default_value'         => '9',
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),

        array(
            'key'                   => 'field_6CjgumMvyzb23cpage',
            'label'                 => esc_attr__('Blog Animation','keymoto'),
            'name'                  => 'blog_animation',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'disable'                =>         esc_attr__('Disable','keymoto'),
                'fadeIn'                 =>         esc_attr__('fadeIn','keymoto'),
                'flipXIn'                =>         esc_attr__('flipXIn','keymoto'),
                'flipYIn'                =>         esc_attr__('flipYIn','keymoto'),
                'flipBounceXIn'          =>         esc_attr__('flipBounceXIn','keymoto'),
                'flipBounceYIn'          =>         esc_attr__('flipBounceYIn','keymoto'),
                'swoopIn'                =>         esc_attr__('swoopIn','keymoto'),
                'raise'                  =>         esc_attr__('raise','keymoto'),
                'whirlIn'                =>         esc_attr__('whirlIn','keymoto'),
                'shrinkIn'               =>         esc_attr__('shrinkIn','keymoto'),
                'expandIn'               =>         esc_attr__('expandIn','keymoto'),
                'bounceIn'               =>         esc_attr__('bounceIn','keymoto'),
                'bounceUpIn'             =>         esc_attr__('bounceUpIn','keymoto'),
                'bounceDownIn'           =>         esc_attr__('bounceDownIn','keymoto'),
                'bounceLeftIn'           =>         esc_attr__('bounceLeftIn','keymoto'),
                'bounceRightIn'          =>         esc_attr__('bounceRightIn','keymoto'),
                'slideUpIn'              =>         esc_attr__('slideUpIn','keymoto'),
                'slideDownIn'            =>         esc_attr__('slideDownIn','keymoto'),
                'slideLeftIn'            =>         esc_attr__('slideLeftIn','keymoto'),
                'slideRightIn'           =>         esc_attr__('slideRightIn','keymoto'),
                'slideUpBigIn'           =>         esc_attr__('slideUpBigIn','keymoto'),
                'slideDownBigIn'         =>         esc_attr__('slideDownBigIn','keymoto'),
                'slideLeftBigIn'         =>         esc_attr__('slideLeftBigIn','keymoto'),
                'slideRightBigIn'        =>         esc_attr__('slideRightBigIn','keymoto'),
                'perspectiveUpIn'        =>         esc_attr__('perspectiveUpIn','keymoto'),
                'perspectiveDownIn'      =>         esc_attr__('perspectiveDownIn','keymoto'),
                'perspectiveLeftIn'      =>         esc_attr__('perspectiveLeftIn','keymoto'),
                'perspectiveRightIn'     =>         esc_attr__('perspectiveRightIn','keymoto'),
                'zoomIn'                 =>         esc_attr__('zoomIn','keymoto'),
                'slideInRightVeryBig'    =>         esc_attr__('slideInRightVeryBig','keymoto'),
                'slideInLeftVeryBig'     =>         esc_attr__('slideInLeftVeryBig','keymoto'),
            ),
            'default_value'         => array(),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),

        array(
            'key'                   => 'field_H3fjCCwsxjwJpcpage',
            'label'                 => esc_attr__('Blog Pagination','keymoto'),
            'name'                  => 'blog_pagination',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'standard'                   => esc_attr__('Default','keymoto'),
                'load_more'                  => esc_attr__('Load More','keymoto'),
            ),
            'default_value' => array(
                0                                   => 'standard',
            ),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),
/*-------------------------------------------------------------------
  ==  Sidebar Setting
  -------------------------------------------------------------------*/
        array(
            'key'                   => 'field_ghYeEwwoh6Qeu',
            'label'                 => '<span class="dashicons dashicons-align-right"></span>'.esc_attr__('Sidebar Setting','keymoto'),
            'name'                  => '',
            'type'                  => 'tab',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'placement'             => 'left',
            'endpoint'              => 0,
        ),
        array(
            'key'                   => 'field_adF1VkIkBqala',
            'label'                 => esc_attr__('Sidebar','keymoto'),
            'name'                  => 'blog_template_sidebar',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'disable'                   => esc_attr__('Disable','keymoto'),
                'left'                      => esc_attr__('Left','keymoto'),
                'right'                     => esc_attr__('Right','keymoto'),
            ),
            'default_value' => array(
                0                                   => 'disable',
            ),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),
    ),
    'location' => array(
        array(
            array(
                'param'                                 => 'page_template',
                'operator'                              => '==',
                'value'                                 => 'template-blog.php',
            ),
        ),
    ),
    'menu_order'                    => 0,
    'position'                      => 'normal',
    'style'                         => 'default',
    'label_placement'               => 'top',
    'instruction_placement'         => 'label',
    'hide_on_screen'                => '',
    'active'                        => 1,
    'description'                   => '',
));